# Generated by Django 3.2.16 on 2024-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_product_user_alter_product_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created_at',), 'verbose_name': 'раздел меню', 'verbose_name_plural': 'Разделы меню (категории)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'блюда/напитки'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.\nНапример: для раздела "Супы" подойдёт идентификатор "soup"', max_length=20, unique=True, verbose_name='Идентификатор'),
        ),
    ]
