# Generated by Django 3.2.16 on 2024-05-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20240531_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restoran',
            options={'ordering': ('created_at',), 'verbose_name': 'Ресторан', 'verbose_name_plural': 'рестораны'},
        ),
        migrations.RenameField(
            model_name='restoran',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='restoran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='basket.restoran', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restoran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='basket.restoran', verbose_name='Ресторан'),
        ),
    ]
