# Generated by Django 3.2.16 on 2024-05-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20240531_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoran',
            name='concept',
            field=models.TextField(blank=True, help_text='Опишите историю создания вашего заведения,его концепцию, особенности.\nВсё, чем оно уникально.', verbose_name='Концепция'),
        ),
        migrations.AddField(
            model_name='restoran',
            name='image',
            field=models.ImageField(blank=True, upload_to='restorants_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='email',
            field=models.EmailField(blank=True, help_text='Укажите электронную почту ресторана.', max_length=50, null=True, verbose_name='Электронная почта'),
        ),
    ]
