# Generated by Django 3.2.16 on 2024-06-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_product_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
