# Generated by Django 3.2.16 on 2024-07-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_restaurant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=64, verbose_name='Выход гр./мл.'),
        ),
    ]
