# Generated by Django 3.2.16 on 2024-07-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gastronomic_pairings',
            field=models.CharField(blank=True, max_length=256, verbose_name='Гастрономические пары'),
        ),
        migrations.AddField(
            model_name='product',
            name='table_setting',
            field=models.CharField(blank=True, max_length=128, verbose_name='Сервировка'),
        ),
    ]
